### ISSUE TITLE
JTable causes editor to go blank

### ISSUE THREAD

**Issue by igarshep** [eclipse-windowbuilder/windowbuilder#632] opened 2023-11-13 17:09 UTC
Not sure what details I can provide to help figure out what's going on, but I'll give a bit of details about my environment: 
OSX 14.1.1 on an Apple M1 Max, Eclipse 2023-09 (4.29.0), using WindowBuilder 1.13.

![image](https://github.com/eclipse-windowbuilder/windowbuilder/assets/30322202/3e47d209-ef7e-4298-bb62-3fec319090cb)

The behavior I'm experiencing is adding a JTable to anything is not possible with the designer (while something like JTree will work), and if I add a simple JTable in the code, the designer view will go blank.

Here is how little code it takes for me to reproduce this issue:

    private JFrame frame;

    /**
     * Create the application.
     */
    public TestView() {
        initialize();
    }

    /**
     * Initialize the contents of the frame.
     */
    private void initialize() {
        frame = new JFrame();
        frame.setBounds(100, 100, 450, 300);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        JScrollPane scrollPane = new JScrollPane();
        //final JTable table = new JTable();
        //scrollPane.setViewportView(table);
        GroupLayout groupLayout = new GroupLayout(frame.getContentPane());
        groupLayout.setHorizontalGroup(
            groupLayout.createParallelGroup(Alignment.LEADING)
                .addGroup(groupLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(scrollPane, GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                    .addContainerGap())
        );
        groupLayout.setVerticalGroup(
            groupLayout.createParallelGroup(Alignment.LEADING)
                .addGroup(groupLayout.createSequentialGroup()
                    .addComponent(scrollPane, GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                    .addContainerGap())
        );
        frame.getContentPane().setLayout(groupLayout);
    }

toggling the first commented out line will cause the editor to go blank
![image](https://github.com/eclipse-windowbuilder/windowbuilder/assets/30322202/ca8746f2-6d1a-4a6a-a78f-2009b13779e4)

**Comment by ptziegler** [comment] 2023-11-14 18:38
I've tried out your snippet but neither with 1.13.0 nor with the nightly build am I able to reproduce this problem. I'm using Linux but I would expect Swing to behave also the same on either platforms.

What Java version are you using?

Are there any compilation errors in your workspace?

Can you upload your error log, in order to detect any unhandled exceptions?

**Comment by igarshep** [comment] 2023-11-14 20:08
I have many different Java's installed, how do I figure out which one you're looking for?

Also, I see no compilation issues.
I'd love to give you an error log as well, but not sure I have what you're looking for. I cleared it and played around with the window builder and got these two issues:
[log.log](https://github.com/eclipse-windowbuilder/windowbuilder/files/13355621/log.log)

**Comment by ptziegler** [comment] 2023-11-14 20:14
> I have many different Javas installed, how do I figure out which one you're looking for?

You can check the execution environment by right-clicking on the project and then go Properties -> Java Build Path -> Right Click on the JRE System Library -> Edit

![image](https://github.com/eclipse-windowbuilder/windowbuilder/assets/70652978/dfb668da-24df-4181-9d4b-604d4002bc2f)

But I don't think that's necessary. The error log already tells me what the problem is:

```
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoClassDefFoundError: java/lang/Compiler [in thread "main"]
	at org.mvel2.compiler.AbstractParser.setupParser(AbstractParser.java:215)
	at org.mvel2.compiler.AbstractParser.<clinit>(AbstractParser.java:153)
	at org.mvel2.MVEL.compileExpression(MVEL.java:827)
	at org.eclipse.wb.internal.core.model.util.ScriptUtils.compile(ScriptUtils.java:230)
	at org.eclipse.wb.internal.core.model.util.ScriptUtils.evaluate(ScriptUtils.java:85)
	at org.eclipse.wb.internal.core.model.util.ScriptUtils.evaluate(ScriptUtils.java:47)
	at org.eclipse.wb.internal.core.model.description.rules.PropertyDefaultRule.getValue(PropertyDefaultRule.java:60)
	at org.eclipse.wb.internal.core.model.description.rules.PropertyDefaultRule.begin(PropertyDefaultRule.java:48)
```

You're using Java 21, which is only fully supported with the upcoming 1.14.0. Your options are to either switch to Java 17 for the time being, or to install the latest milestone build:
 https://download.eclipse.org/windowbuilder/updates/milestone/S202311141707

**Comment by igarshep** [comment] 2023-11-14 20:31
Interestingly enough, I was already just at 17. However, the milestone build seems to have fixed it for me. Anything I need to be careful about when using the current milestone build?

**Comment by ptziegler** [comment] 2023-11-14 20:39
> Anything I need to be careful about when using the current milestone build?

There was quite a lot of work done with the GEF migration, but ideally that's now something that will be visible to the user. If you're experiencing anything odd in the design page, please let me know. Otherwise it should (hopefully) behave exactly the same.

Given that the problem doesn't seen to show up with the 1.14.0, I'm closing this one as fixed.

**Closed by ptziegler** 2023-11-14 20:39 UTC
