### ISSUE TITLE
install new ver windowbuilder e (I got poblem with that )

### ISSUE THREAD

**Issue by phungxHuy** [eclipse-windowbuilder/windowbuilder#590] opened 2023-10-07 16:52 UTC
![pic1](https://github.com/eclipse-windowbuilder/windowbuilder/assets/147267929/dad23192-082a-4323-a66e-0e456c35654c)

**Comment by ptziegler** [comment] 2023-10-07 17:13
Which update site are you using?
Which version of WindowBuilder are you trying to install?

Given that the Eclipse seems to be unable to find MVEL 2.5.0, I assume you're trying to install the 1.14.0 M1?
The bundle should be uploaded to this p2 repository here:  https://download.eclipse.org/windowbuilder/updates/milestone/S202310020533
Can you give that one a go?

**Comment by merks** [comment] 2023-10-07 17:45
This is typically caused by p2 having some inconsistency between the content metadata (what installable units are available) and the artifact metadata (where is the jar associated with that unit).   A broken update site could cause that, but most often it's just some in-memory caching involved.  First try to restart the IDE and try again.  If the same problem happens,  try Window -> Preferences -> Oomph -> Bundle Pools -> Clear Cache...  That should force loading everything fresh directly from the internet...  The jar definitely exists at the above mentioned location:

**Comment by phungxHuy** [comment] 2023-10-08 02:48
I am  trying install ver 1.13 ( latest)  for my win10.

**Comment by phungxHuy** [comment] 2023-10-08 03:19
should I install windowb in java market ?

**Comment by merks** [comment] 2023-10-08 05:46
You didn't say which update site URL you are using and you didn't appear to have tried what I suggested. 

Did you try what I suggested?  Which update site are you trying to use?

**Comment by phungxHuy** [comment] 2023-10-08 09:07
I copy link install windowb from eclip site then I install it in eclip app . I don not sure your link to do what, can you explain for me ? . sorry , i am new learner :))

**Comment by merks** [comment] 2023-10-08 12:32
Use the menu to open the preferences Window -> Preferences -> Oomph -> Bundle Pools -> Clear Cache... and press this button:

![image](https://github.com/eclipse-windowbuilder/windowbuilder/assets/208716/9a8974af-771f-4b1d-80d4-d583c24175c3)

**Comment by phungxHuy** [comment] 2023-10-08 12:58
then i can install again ?

**Comment by merks** [comment] 2023-10-08 13:06
Yes, you can try again.  Restart the IDE too, just for good luck.

**Comment by phungxHuy** [comment] 2023-10-08 15:46
It's still error 😃 . Any solutions ?

**Comment by ptziegler** [comment] 2023-10-09 18:48
Maybe we should take one step back... What's the process with which you install WindowBuilder?

The normal workflow should be:

-> Help -> Install New Software...
-> Enter https://download.eclipse.org/windowbuilder/updates/release/1.13.0
-> Select all WindowBuilder features

![image](https://github.com/eclipse-windowbuilder/windowbuilder/assets/70652978/b1f0ca1f-7812-4921-935c-fde3a3fbbd3f)

If that doesn't work, I'd consider cleanup up/disabling some of the p2 software sites. Perhaps a bad URL snuck its way in and is now causing problems.

![image](https://github.com/eclipse-windowbuilder/windowbuilder/assets/70652978/d90bfdb8-2253-4d6e-95d5-4cff55552890)

As a last option, I would suggest installing WindowBuilder in a fresh Eclipse environment.

**Comment by ptziegler** [comment] 2024-06-20 16:36
I'm closing this one. As Ed mentioned, this issue is likely caused by an inconsistent cache and should be fixed by clearing the caches. In general, I can't reproduce this in a clean installation.

Feel free to reopen this issue if you think it is still relevant.

**Closed by ptziegler** 2024-06-20 16:36 UTC
Labels: question
