### ISSUE TITLE
WindowBuilder class not found exception and solution

### ISSUE THREAD

**Issue by Bio7** [eclipse-windowbuilder/windowbuilder#530] opened 2023-08-06 11:27 UTC
I have an RCP application in which the WindowBuilder can be installed from the p2 Update Manager. Since one of the latest releases the builder is workin again after changes of some libraries (see [forum post](https://github.com/eclipse-windowbuilder/windowbuilder/discussions/172)).

However when I opened a self created layout with two tabs and some components when I opened the second tab I received a class not found exception. Here the relevant part:

java.lang.NoClassDefFoundError: org/mvel2/compiler/Accessor
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1013)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:875)
	at org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer$ContextClassLoader.defineClass(ASMAccessorOptimizer.java:2321)
	at org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer.loadClass(ASMAccessorOptimizer.java:2332)
	at org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer._initializeAccessor(ASMAccessorOptimizer.java:814)
	at org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer.compileAccessor(ASMAccessorOptimizer.java:957)
	at org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer.optimizeAccessor(ASMAccessorOptimizer.java:345)
	at org.mvel2.optimizers.dynamic.DynamicGetAccessor.optimize(DynamicGetAccessor.java:95)
	at org.mvel2.optimizers.dynamic.DynamicGetAccessor.getValue(DynamicGetAccessor.java:65)
	at org.mvel2.ast.ASTNode.getReducedValueAccelerated(ASTNode.java:108)
	at org.mvel2.ast.BinaryOperation.getReducedValueAccelerated(BinaryOperation.java:146)
	at org.mvel2.ast.And.getReducedValueAccelerated(And.java:34)
	at org.mvel2.compiler.ExecutableAccessor.getValue(ExecutableAccessor.java:38)
	at org.mvel2.ast.ReturnNode.getReducedValueAccelerated(ReturnNode.java:52)
	at org.mvel2.compiler.ExecutableAccessor.getValue(ExecutableAccessor.java:38)
	at org.mvel2.ast.IfNode.getReducedValueAccelerated(IfNode.java:74)
	at org.mvel2.MVELRuntime.execute(MVELRuntime.java:85)
	at org.mvel2.compiler.CompiledExpression.getDirectValue(CompiledExpression.java:115)
	at org.mvel2.compiler.CompiledExpression.getValue(CompiledExpression.java:111)
	at org.mvel2.MVEL.executeExpression(MVEL.java:985)
	at org.eclipse.wb.internal.core.model.util.ScriptUtils.evaluate(ScriptUtils.java:147)
	at org.eclipse.wb.internal.core.model.util.ScriptUtils.evaluate(ScriptUtils.java:86)
	at org.eclipse.wb.internal.swt.model.layout.LayoutDataInfo$6.isDefault(LayoutDataInfo.java:313)
	at org.eclipse.wb.internal.swt.model.layout.LayoutDataInfo$6.endEdit_aboutToRefresh(LayoutDataInfo.java:299)

From this error I deduced that mvel  was missing on the classpath. So I searched for this library and found it:

https://mvnrepository.com/artifact/org.mvel/mvel2/2.5.0.Final

I added it to the module classpath of my RCP (I have a bundled JDK) and the error was finally gone.

Could it be possible that this is a general missing WindowBuilder library?

**Comment by ptziegler** [comment] 2023-08-07 05:29
Hm... I assume this is a side-effect of replacing the embedded MVEL jar with the official Maven release, which I did as part of be7cead7f5e9eeff112a3d35a5f9b947ba8fcc77. The new bundle should be part of the WindowBuilder installation, so normally, it shouldn't be necessary to explicitly add it to the classpath.

Can you provide a small reproducer so that I can test this further?

**Comment by Bio7** [comment] 2023-08-07 15:12
I stripped down a GUI which produces this exception in a regular Eclipse SWT project without any custom RCP app dependencies (see Java class attachment below as *.txt)
[_ModelGui.txt](https://github.com/eclipse-windowbuilder/windowbuilder/files/12281522/_ModelGui.txt)

If you double click on the second tab the exception will be thrown.

If you delete line 473  `featureLabel.setLayoutData(new GridData(SWT.FILL, SWT.FILL, true, false, 2, 1));
` it will not throw the exception. 

Strangely it works also if you delete other GUI elements above.

I tested this in Eclipse on Windows 2023-03 with the latest WB release (1.13)

**Comment by ptziegler** [comment] 2023-08-07 19:24
Awesome! Thank you a lot.

The exception seems to be thrown by MVEL while trying to load a certain "ASMAccessorImpl_\<random-integer\>", which  seems like an internal class created by MVEL itself. Furthermore, it's a lot harder to trigger this exception while debugging, so I'm suspecting timing and classloader loading/unloading within MVEL to be the primary factor.

A quick search lead me to https://github.com/mvel/mvel/issues/194, which seems to describe exactly what you're experiencing. Sadly, without any result. I find it weird that the problem no longer showed up after you added MVEL to the classpath, but that might've simply tweaked the timing in a favorable behavior.

The issue was reported with MVEL 2.4.3. Over the next few days, I'll try to see if it also shows up with an older versions. Alternatively, I can also try to synchronize calls to MVEL. But right now, I know too little about this library to say for certain what's causing this :(

**Comment by Bio7** [comment] 2023-08-07 19:35
Great. I have to thank for looking into this.

**Comment by ptziegler** [comment] 2023-08-10 16:45
Fixed with #534 
It seems like my initial guess was wrong. MVEL internally loads an instance of Accessor using a different classloader than what's used to call it. This classloader is based on the project classloader and thus doesn't have MVEL in its classpath, hence the exception.
Which means your initial guess was correct and also the reason why manually adding it to the classpath resolves the problem.
The problematic part of the code is only called occasionally, for reasons that I simply don't know. Which is also why I can't simplify your example any further and create an integration test for it. :/
In any case, the solution is the same as yours: To make sure MVEL is part of the project classloader.

**Closed** 2023-08-10 16:45 UTC
Labels: bug

**Comment by Bio7** [comment] 2023-08-10 16:55
Top. Thanks for fixing this so fast!
