### ISSUE TITLE
WindowBuilder was not able to show the GUI

### ISSUE THREAD

**Issue by CindyCASC** [eclipse-windowbuilder/windowbuilder#533] opened 2023-08-09 12:45 UTC
I upgraded from Eclipse Neon which was not having any problems to Eclipse 2023-06.  Since then, I have issues when using GridBagLayout.  Every time I use the Pallet to drop a component onto my JPanel.  If I try to change a label text or rename a component I get errors.

I added a new label and tried to set the text and got this error.
Internal Error
WindowBuilder encountered unexpected internal error. 
This could be caused by a WindowBuilder bug or by a misconfiguration issue, conflict, partialupdate, etc.
org.eclipse.wb.internal.core.utils.check.AssertionFailedException: assertion failed

If I try to Delete Contents of a row or Delete Row I get this error
Internal Error
WindowBuilder encountered unexpected internal error. 
This could be caused by a WindowBuilder bug or by a misconfiguration issue, conflict, partialupdate, etc.
java.lang.IndexOutOfBoundsException: Index: 1, Length: 0

I have tried to update WindowBuilder and check all plugins and settings I can think of.

Can anyone offer any suggestions on resolving this issue?
[Eclipse_WindowBuilder_bugs.txt](https://github.com/eclipse-windowbuilder/windowbuilder/files/12302695/Eclipse_WindowBuilder_bugs.txt)

**Comment by ptziegler** [comment] 2023-08-10 04:58
I remember seeing a similar error a few months ago, but I was never able to reliably reproduce it. Would it be possible for you to provide a small example? I've just created a simple panel and there drag & drop works with the GridBagLayout, so I assume it only shows up under certain circumstances.

Which WindowBuilder version did you upgrade from?

**Comment by CindyCASC** [comment] 2023-08-10 15:45
Patrick,

Just incase this helps I added two more screen shots.

Neon
***@***.***
2023-06
***@***.***

***@***.***
Cindy Cunningham
Programmer Analyst

Email: ***@***.******@***.***>
Phone: 517-266-5145


906 James St, Adrian, MI 49221

www.adriansteel.com<http://www.adriansteel.com/>


From: Patrick Ziegler ***@***.***>
Sent: Thursday, August 10, 2023 12:59 AM
To: eclipse-windowbuilder/windowbuilder ***@***.***>
Cc: Cindy Cunningham ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [eclipse-windowbuilder/windowbuilder] WindowBuilder was not able to show the GUI (Issue #533)

You don't often get email from ***@***.******@***.***>. Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

I remember seeing a similar error a few months ago, but I was never able to reliably reproduce it. Would it be possible for you to provide a small example? I've just created a simple panel and there drag & drop works with the GridBagLayout, so I assume it only shows up under certain circumstances.

Which WindowBuilder version did you upgrade from?

-

**Comment by CindyCASC** [comment] 2023-08-14 12:30
Patrick,

I must apologize.  I was so intent on making sure you had the Eclipse information that I did not send you the example code.  I hope this helps.

MyTestApp I added a JTabbedPane and pnlEast with GridBagLayout.

When I try to delete the JTabbedPane I get this error.
***@***.***

I cannot Delete the new label on the pnlEast (GridBagLayout)

If it try to change pnlEast from a GridBagLayout back to FlowLayout or or any other layout I get this error.
***@***.***

***@***.***
Cindy Cunningham
Programmer Analyst

Email: ***@***.******@***.***>
Phone: 517-266-5145


906 James St, Adrian, MI 49221

www.adriansteel.com<http://www.adriansteel.com/>


From: Patrick Ziegler ***@***.***>
Sent: Thursday, August 10, 2023 12:59 AM
To: eclipse-windowbuilder/windowbuilder ***@***.***>
Cc: Cindy Cunningham ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [eclipse-windowbuilder/windowbuilder] WindowBuilder was not able to show the GUI (Issue #533)

You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

I remember seeing a similar error a few months ago, but I was never able to reliably reproduce it. Would it be possible for you to provide a small example? I've just created a simple panel and there drag & drop works with the GridBagLayout, so I assume it only shows up under certain circumstances.

Which WindowBuilder version did you upgrade from?

-

**Comment by CindyCASC** [comment] 2023-08-14 12:33
Patrick,

My Monday is really not starting out well.  I forgot to attach the source.



***@***.***
Cindy Cunningham
Programmer Analyst

Email: ***@***.******@***.***>
Phone: 517-266-5145


906 James St, Adrian, MI 49221

www.adriansteel.com<http://www.adriansteel.com/>


From: Patrick Ziegler ***@***.***>
Sent: Thursday, August 10, 2023 12:59 AM
To: eclipse-windowbuilder/windowbuilder ***@***.***>
Cc: Cindy Cunningham ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [eclipse-windowbuilder/windowbuilder] WindowBuilder was not able to show the GUI (Issue #533)

You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

I remember seeing a similar error a few months ago, but I was never able to reliably reproduce it. Would it be possible for you to provide a small example? I've just created a simple panel and there drag & drop works with the GridBagLayout, so I assume it only shows up under certain circumstances.

Which WindowBuilder version did you upgrade from?

-

**Comment by ptziegler** [comment] 2023-08-15 06:11
Hm, it seems like none of the attachments are uploaded to GitHub if you send them via mail :/

I've tried to reproduce this issue locally over the past few days, but without success. So the source code would be greatly appreciated. It might also help if you could zip the entire project and upload it, given that the culprit might also be some persisted metadata that doesn't play nice.

**Comment by CindyCASC** [comment] 2023-08-15 12:42
Patrick,

Hope these attachments help.

Options for saving only offer "Close with comment".  Please do not close.

[MyTestApp.docx](https://github.com/eclipse-windowbuilder/windowbuilder/files/12344057/MyTestApp.docx)
[Emails.docx](https://github.com/eclipse-windowbuilder/windowbuilder/files/12344113/Emails.docx)

**Comment by CindyCASC** [comment] 2023-08-15 12:43
Please keep this open

**Comment by CindyCASC** [comment] 2023-08-15 12:45
Patrick,

Attachments uploaded in GitHub but only option was "Close with comment"

Please keep me updated.

Thank you

***@***.***
Cindy Cunningham
Programmer Analyst

Email: ***@***.******@***.***>
Phone: 517-442-1981


906 James St, Adrian, MI 49221

www.adriansteel.com<http://www.adriansteel.com/>


From: Patrick Ziegler ***@***.***>
Sent: Tuesday, August 15, 2023 2:12 AM
To: eclipse-windowbuilder/windowbuilder ***@***.***>
Cc: Cindy Cunningham ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [eclipse-windowbuilder/windowbuilder] WindowBuilder was not able to show the GUI (Issue #533)

You don't often get email from ***@***.******@***.***>. Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

Hm, it seems like none of the attachments are uploaded to GitHub if you send them via mail :/

I've tried to reproduce this issue locally over the past few days, but without success. So the source code would be greatly appreciated. It might also help if you could zip the entire project and upload it, given that the culprit might also be some persisted metadata that doesn't play nice.

-

**Comment by ptziegler** [comment] 2023-08-15 18:49
> Attachments uploaded in GitHub but only option was "Close with comment"

You should be able to attach files via drag & drop and GitHub should automatically upload them.

![image](https://github.com/eclipse-windowbuilder/windowbuilder/assets/70652978/843385a3-5240-4e3a-8db8-071055b7c654)

In any case, I think I have a rough idea what's happening, I just don't understand _why_ it's happening and why it's not happening on my side, even when using your code example.

I've created #546 which hopefully handles this error a little bit more gracefully. If there are no regressions, there should be a build available tomorrow that _might_ fix this problem.

**Comment by CindyCASC** [comment] 2023-08-15 18:51
Sounds hopeful.

Thank you for the update.

***@***.***
Cindy Cunningham
Programmer Analyst

Email: ***@***.******@***.***>
Phone: 517-442-1981


906 James St, Adrian, MI 49221

www.adriansteel.com<http://www.adriansteel.com/>


From: Patrick Ziegler ***@***.***>
Sent: Tuesday, August 15, 2023 2:49 PM
To: eclipse-windowbuilder/windowbuilder ***@***.***>
Cc: Cindy Cunningham ***@***.***>; State change ***@***.***>
Subject: [EXTERNAL] Re: [eclipse-windowbuilder/windowbuilder] WindowBuilder was not able to show the GUI (Issue #533)

You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

Attachments uploaded in GitHub but only option was "Close with comment"

You should be able to attach files via drag & drop and GitHub should automatically upload them.

[Image removed by sender. image]<https://user-images.githubusercontent.com/70652978/260807175-843385a3-5240-4e3a-8db8-071055b7c654.png>

In any case, I think I have a rough idea what's happening, I just don't understand why it's happening and why it's not happening on my side, even when using your code example.

I've created #546<https://github.com/eclipse-windowbuilder/windowbuilder/pull/546> which hopefully handles this error a little bit more gracefully. If there are no regressions, there should be a build available tomorrow that might fix this problem.

-

**Comment by CindyCASC** [comment] 2023-09-06 20:45
Patrick,

The patch you created appears to prevent the hard errors.

The issue still remains in GridBagLayout I cannot delete any components that have been added.

It will not stop development because I can edit directly in the source but I sure would be nice to have that functionality back.


***@***.***
Cindy Cunningham
Programmer Analyst

Email: ***@***.******@***.***>
Phone: 517-442-1981


906 James St, Adrian, MI 49221

www.adriansteel.com<http://www.adriansteel.com/>


From: Patrick Ziegler ***@***.***>
Sent: Tuesday, August 15, 2023 2:49 PM
To: eclipse-windowbuilder/windowbuilder ***@***.***>
Cc: Cindy Cunningham ***@***.***>; State change ***@***.***>
Subject: [EXTERNAL] Re: [eclipse-windowbuilder/windowbuilder] WindowBuilder was not able to show the GUI (Issue #533)

You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

Attachments uploaded in GitHub but only option was "Close with comment"

You should be able to attach files via drag & drop and GitHub should automatically upload them.

[Image removed by sender. image]<https://user-images.githubusercontent.com/70652978/260807175-843385a3-5240-4e3a-8db8-071055b7c654.png>

In any case, I think I have a rough idea what's happening, I just don't understand why it's happening and why it's not happening on my side, even when using your code example.

I've created #546<https://github.com/eclipse-windowbuilder/windowbuilder/pull/546> which hopefully handles this error a little bit more gracefully. If there are no regressions, there should be a build available tomorrow that might fix this problem.

-

**Comment by ptziegler** [comment] 2023-09-07 04:51
Hi Cindy. Sorry, I lost track of this problem. But the general problem is that I just can't reproduce this exception, so I have a really hard time coming up with a solution...

Perhaps let's try to reproduce this in a more controlled environment. I think you're using the Eclipse IDE. Can you instead try to download and install the Eclipse SDK?
https://download.eclipse.org/eclipse/downloads/drops4/R-4.28-202306050440/

Just download & unpack the zip archive for your operating system.
![image](https://github.com/eclipse-windowbuilder/windowbuilder/assets/70652978/c7d8bb8c-be4c-41bd-adf3-b74f008cf069)

Then install the latest WindowBuilder milestone
https://download.eclipse.org/windowbuilder/updates/milestone/S202309051601/

Then open this test widget:
```
package com.adriansteel.test;

import java.awt.GraphicsConfiguration;
import java.awt.HeadlessException;

import javax.swing.JPanel;
import java.awt.BorderLayout;
import java.awt.GridBagLayout;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;
import javax.swing.border.EmptyBorder;
import javax.swing.JButton;
import javax.swing.JFrame;

import java.awt.GridBagConstraints;
import java.awt.FlowLayout;
import javax.swing.JLabel;
import java.awt.Insets;

public class MyTestApp extends JFrame {
	private JPanel pnlNorth;
	private JTabbedPane tabbedPane;
	private JTextField textField;
	private JPanel pnlEast;
	private JPanel pnlSouth;
	private JButton btnNewButton;
	private JLabel lblNewLabel;
	private JLabel lblNewLabel_1;

	public MyTestApp() throws HeadlessException {
		getContentPane().add(getPnlNorth(), BorderLayout.NORTH);
		getContentPane().add(getTabbedPane(), BorderLayout.CENTER);
		getContentPane().add(getPnlEast(), BorderLayout.EAST);
		getContentPane().add(getPnlSouth(), BorderLayout.SOUTH);
		// TODO Auto-generated constructor stub
	}

	public MyTestApp(GraphicsConfiguration arg0) {
		super(arg0);
		// TODO Auto-generated constructor stub
	}

	public MyTestApp(String arg0) throws HeadlessException {
		super(arg0);
		// TODO Auto-generated constructor stub
	}

	public MyTestApp(String arg0, GraphicsConfiguration arg1) {
		super(arg0, arg1);
		// TODO Auto-generated constructor stub
	}

	public static void main(String[] args) {
		// TODO Auto-generated method stub

	}

	private JPanel getPnlNorth() {
		if (pnlNorth == null) {
			pnlNorth = new JPanel();
			pnlNorth.setLayout(new BorderLayout(0, 0));
			pnlNorth.add(getTextField(), BorderLayout.NORTH);
		}
		return pnlNorth;
	}
	private JTabbedPane getTabbedPane() {
		if (tabbedPane == null) {
			tabbedPane = new JTabbedPane(JTabbedPane.TOP);
		}
		return tabbedPane;
	}
	private JTextField getTextField() {
		if (textField == null) {
			textField = new JTextField();
		}
		return textField;
	}
	private JPanel getPnlEast() {
		if (pnlEast == null) {
			pnlEast = new JPanel();
			GridBagLayout gbl_pnlEast = new GridBagLayout();
			gbl_pnlEast.columnWidths = new int[] {0, 0};
			gbl_pnlEast.rowHeights = new int[] {0, 0, 0};
			gbl_pnlEast.columnWeights = new double[]{0.0, Double.MIN_VALUE};
			gbl_pnlEast.rowWeights = new double[]{0.0, 0.0, Double.MIN_VALUE};
			pnlEast.setLayout(gbl_pnlEast);
			GridBagConstraints gbc_lblNewLabel = new GridBagConstraints();
			gbc_lblNewLabel.insets = new Insets(0, 0, 5, 0);
			gbc_lblNewLabel.gridx = 0;
			gbc_lblNewLabel.gridy = 0;
			pnlEast.add(getLblNewLabel(), gbc_lblNewLabel);
			GridBagConstraints gbc_lblNewLabel_1 = new GridBagConstraints();
			gbc_lblNewLabel_1.gridx = 0;
			gbc_lblNewLabel_1.gridy = 1;
			pnlEast.add(getLblNewLabel_1(), gbc_lblNewLabel_1);
		}
		return pnlEast;
	}
	private JPanel getPnlSouth() {
		if (pnlSouth == null) {
			pnlSouth = new JPanel();
			pnlSouth.add(getBtnNewButton());
		}
		return pnlSouth;
	}
	private JButton getBtnNewButton() {
		if (btnNewButton == null) {
			btnNewButton = new JButton("New button");
		}
		return btnNewButton;
	}
	private JLabel getLblNewLabel() {
		if (lblNewLabel == null) {
			lblNewLabel = new JLabel("New label");
		}
		return lblNewLabel;
	}
	private JLabel getLblNewLabel_1() {
		if (lblNewLabel_1 == null) {
			lblNewLabel_1 = new JLabel("New label");
		}
		return lblNewLabel_1;
	}
}
```
If you open this in design page and try to delete "New label", does the error still show up?

**Comment by CindyCASC** [comment] 2023-09-07 14:23
Patrick,

I downloaded but could not install the JDK you listed.

I am getting "Version 1.8.0_144 of the JVM is not suitable for this product.  Version 17 or greater is required."

I don't know my next step.  I may want to install on a different PC so I don't corrupt my current system.

I will be in touch.

***@***.***
Cindy Cunningham
Programmer Analyst

Email: ***@***.******@***.***>
Phone: 517-442-1981


906 James St, Adrian, MI 49221

www.adriansteel.com<http://www.adriansteel.com/>


From: Patrick Ziegler ***@***.***>
Sent: Thursday, September 7, 2023 12:52 AM
To: eclipse-windowbuilder/windowbuilder ***@***.***>
Cc: Cindy Cunningham ***@***.***>; State change ***@***.***>
Subject: [EXTERNAL] Re: [eclipse-windowbuilder/windowbuilder] WindowBuilder was not able to show the GUI (Issue #533)

You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

Hi Cindy. Sorry, I lost track of this problem. But the general problem is that I just can't reproduce this exception, so I have a really hard time coming up with a solution...

Perhaps let's try to reproduce this in a more controlled environment. I think you're using the Eclipse IDE. Can you instead try to download and install the Eclipse SDK?
https://download.eclipse.org/eclipse/downloads/drops4/R-4.28-202306050440/

Just download & unpack the zip archive for your operating system.
[Image removed by sender. image]<https://user-images.githubusercontent.com/70652978/266206308-c7d8bb8c-be4c-41bd-adf3-b74f008cf069.png>

Then install the latest WindowBuilder milestone
https://download.eclipse.org/windowbuilder/updates/milestone/S202309051601/

Then open this test widget:

package com.adriansteel.test;



import java.awt.GraphicsConfiguration;

import java.awt.HeadlessException;



import javax.swing.JPanel;

import java.awt.BorderLayout;

import java.awt.GridBagLayout;

import javax.swing.JTabbedPane;

import javax.swing.JTextField;

import javax.swing.border.EmptyBorder;

import javax.swing.JButton;

import javax.swing.JFrame;



import java.awt.GridBagConstraints;

import java.awt.FlowLayout;

import javax.swing.JLabel;

import java.awt.Insets;



public class MyTestApp extends JFrame {

        private JPanel pnlNorth;

        private JTabbedPane tabbedPane;

        private JTextField textField;

        private JPanel pnlEast;

        private JPanel pnlSouth;

        private JButton btnNewButton;

        private JLabel lblNewLabel;

        private JLabel lblNewLabel_1;



        public MyTestApp() throws HeadlessException {

               getContentPane().add(getPnlNorth(), BorderLayout.NORTH);

               getContentPane().add(getTabbedPane(), BorderLayout.CENTER);

               getContentPane().add(getPnlEast(), BorderLayout.EAST);

               getContentPane().add(getPnlSouth(), BorderLayout.SOUTH);

               // TODO Auto-generated constructor stub

        }



        public MyTestApp(GraphicsConfiguration arg0) {

               super(arg0);

               // TODO Auto-generated constructor stub

        }



        public MyTestApp(String arg0) throws HeadlessException {

               super(arg0);

               // TODO Auto-generated constructor stub

        }



        public MyTestApp(String arg0, GraphicsConfiguration arg1) {

               super(arg0, arg1);

               // TODO Auto-generated constructor stub

        }



        public static void main(String[] args) {

               // TODO Auto-generated method stub



        }



        private JPanel getPnlNorth() {

               if (pnlNorth == null) {

                       pnlNorth = new JPanel();

                       pnlNorth.setLayout(new BorderLayout(0, 0));

                       pnlNorth.add(getTextField(), BorderLayout.NORTH);

               }

               return pnlNorth;

        }

        private JTabbedPane getTabbedPane() {

               if (tabbedPane == null) {

                       tabbedPane = new JTabbedPane(JTabbedPane.TOP);

               }

               return tabbedPane;

        }

        private JTextField getTextField() {

               if (textField == null) {

                       textField = new JTextField();

               }

               return textField;

        }

        private JPanel getPnlEast() {

               if (pnlEast == null) {

                       pnlEast = new JPanel();

                       GridBagLayout gbl_pnlEast = new GridBagLayout();

                       gbl_pnlEast.columnWidths = new int[] {0, 0};

                       gbl_pnlEast.rowHeights = new int[] {0, 0, 0};

                       gbl_pnlEast.columnWeights = new double[]{0.0, Double.MIN_VALUE};

                       gbl_pnlEast.rowWeights = new double[]{0.0, 0.0, Double.MIN_VALUE};

                       pnlEast.setLayout(gbl_pnlEast);

                       GridBagConstraints gbc_lblNewLabel = new GridBagConstraints();

                       gbc_lblNewLabel.insets = new Insets(0, 0, 5, 0);

                       gbc_lblNewLabel.gridx = 0;

                       gbc_lblNewLabel.gridy = 0;

                       pnlEast.add(getLblNewLabel(), gbc_lblNewLabel);

                       GridBagConstraints gbc_lblNewLabel_1 = new GridBagConstraints();

                       gbc_lblNewLabel_1.gridx = 0;

                       gbc_lblNewLabel_1.gridy = 1;

                       pnlEast.add(getLblNewLabel_1(), gbc_lblNewLabel_1);

               }

               return pnlEast;

        }

        private JPanel getPnlSouth() {

               if (pnlSouth == null) {

                       pnlSouth = new JPanel();

                       pnlSouth.add(getBtnNewButton());

               }

               return pnlSouth;

        }

        private JButton getBtnNewButton() {

               if (btnNewButton == null) {

                       btnNewButton = new JButton("New button");

               }

               return btnNewButton;

        }

        private JLabel getLblNewLabel() {

               if (lblNewLabel == null) {

                       lblNewLabel = new JLabel("New label");

               }

               return lblNewLabel;

        }

        private JLabel getLblNewLabel_1() {

               if (lblNewLabel_1 == null) {

                       lblNewLabel_1 = new JLabel("New label");

               }

               return lblNewLabel_1;

        }

}

If you open this in design page and try to delete "New label", does the error still show up?

-

**Comment by ptziegler** [comment] 2023-09-08 05:00
> I downloaded but could not install the JDK you listed. I am getting "Version 1.8.0_144 of the JVM is not suitable for this product. Version 17 or greater is required."

You can also install the Eclipse SDK via the installer. This should then automatically install the required JDK as well:
https://www.eclipse.org/downloads/packages/installer

Just scroll down until you get to the SDK entry and the installer should do the rest.
![image](https://github.com/eclipse-windowbuilder/windowbuilder/assets/70652978/f25f316e-8fa4-42c5-a292-af4f60db828a)

**Comment by CindyCASC** [comment] 2023-10-10 18:19
I tried to install Eclipse on my laptop just to see if a clean install has the same issues as my regular PC and I got this.
***@***.***

Then I installed Eclipse IDE and JDK 1.8 and JKD 17 because I need to build with 1.8.0
Changed my eclipse.ini file

Now my Eclipse opens but when I try to Open With WindowBuilder Editor I do not get a Design tab.

I am getting very frustrated and am ready to just go back to Neon.

Is there any help that you can offer?


***@***.***
Cindy Cunningham
Programmer Analyst

Email: ***@***.******@***.***>
Phone: 517-442-1981


906 James St, Adrian, MI 49221

www.adriansteel.com<http://www.adriansteel.com/>


From: Patrick Ziegler ***@***.***>
Sent: Friday, September 8, 2023 1:01 AM
To: eclipse-windowbuilder/windowbuilder ***@***.***>
Cc: Cindy Cunningham ***@***.***>; State change ***@***.***>
Subject: [EXTERNAL] Re: [eclipse-windowbuilder/windowbuilder] WindowBuilder was not able to show the GUI (Issue #533)

You don't often get email from ***@***.******@***.***>. Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

I downloaded but could not install the JDK you listed. I am getting "Version 1.8.0_144 of the JVM is not suitable for this product. Version 17 or greater is required."

You can also install the Eclipse SDK via the installer. This should then automatically install the required JDK as well:
https://www.eclipse.org/downloads/packages/installer

Just scroll down until you get to the SDK entry and the installer should do the rest.
[image]<https://user-images.githubusercontent.com/70652978/266506399-f25f316e-8fa4-42c5-a292-af4f60db828a.png>

-

**Comment by ptziegler** [comment] 2023-10-10 19:00
Hold on... you're using an _actual_ Java 8? 

That explains a lot. And if I switch to such an old Java version, I get exactly the same error... Internally, we're using the native Eclipse compiler to process the Java code, which is build (and tested) against Java 17.
My guess is that this is an incompatibility that was introduced at some point during their development cycle. And given that this doesn't show up with newer versions, not something that is likely to get fixed.

> because I need to build with 1.8.0

I think it's just not possible anymore to run recent versions WindowBuilder with Java 8, meaning you need to migrate to a newer Java version, if you want to use it.

If you _need_ to run the code with Java 8, then you could instead set the compiler compliance of your Eclipse project to 1.8. The resulting code should then still be executable with Java 8, even though it was compiled with a newer version.

![image](https://github.com/eclipse-windowbuilder/windowbuilder/assets/70652978/7d526468-b3a0-4b4e-b132-6d477f95b7e7)

**Comment by CindyCASC** [comment] 2023-10-10 19:11
I did a clean install with Java 17 on a completely different computer.  Installed WindowBuilder and can not get the Design tab.  Even without attempting to set my compiler to Java 8.

Is Neon still available if we want to revert back?



***@***.***
Cindy Cunningham
Programmer Analyst

Email: ***@***.******@***.***>
Phone: 517-442-1981


906 James St, Adrian, MI 49221

www.adriansteel.com<http://www.adriansteel.com/>


From: Patrick Ziegler ***@***.***>
Sent: Tuesday, October 10, 2023 3:01 PM
To: eclipse-windowbuilder/windowbuilder ***@***.***>
Cc: Cindy Cunningham ***@***.***>; State change ***@***.***>
Subject: [EXTERNAL] Re: [eclipse-windowbuilder/windowbuilder] WindowBuilder was not able to show the GUI (Issue #533)

You don't often get email from ***@***.******@***.***>. Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

Hold on... you're using an actual Java 8?

That explains a lot. And if I switch to such an old Java version, I get exactly the same error... Internally, we're using the native Eclipse compiler to process the Java code, which is build (and tested) against Java 17.
My guess is that this is an incompatibility that was introduced at some point during their development cycle. And given that this doesn't show up with newer versions, not something that is likely to get fixed.

because I need to build with 1.8.0

I think it's just not possible anymore to run recent versions WindowBuilder with Java 8, meaning you need to migrate to a newer Java version, if you want to use it.

If you need to run the code with Java 8, then you could instead set the compiler compliance of your Eclipse project to 1.8. The resulting code should then still be executable with Java 8, even though it was compiled with a newer version.

[image]<https://user-images.githubusercontent.com/70652978/274032564-7d526468-b3a0-4b4e-b132-6d477f95b7e7.png>

-

**Comment by ptziegler** [comment] 2023-10-10 19:15
> Installed WindowBuilder and can not get the Design tab.  Even without attempting to set my compiler to Java 8.

What's the error you got? If you've attached a screenshot to previous your email, then it hasn't been uploaded to GitHub.

> Is Neon still available if we want to revert back?

The release will always be available for the foreseeable future: https://www.eclipse.org/downloads/packages/release/Neon/3
There is just no guarantee that it'll be compatible with the latest WindowBuilder, though.

**Comment by CindyCASC** [comment] 2023-10-10 19:38
The screen shot said something like...
A Java Runtime Environment (JRE) or Java Development Kit (JDK)
Must be available in order to run Eclipse..... so I installed the JDK 17.

But that was just to launch Eclipse.

According to what you said all of the newer versions of Eclipse cannot be used to build over Java 8 so I guess we are stuck with reverting back to Neon.

I appreciate your response.  Just wish we would have know that earlier or I would have never upgraded.

We are going to be going thru some process changes here so hopefully we will get away from Java 8.  Unfortunately I don't think that will be nearly soon enough.

Thanks again for your prompt feedback.

Cindy


***@***.***
Cindy Cunningham
Programmer Analyst

Email: ***@***.******@***.***>
Phone: 517-442-1981


906 James St, Adrian, MI 49221

www.adriansteel.com<http://www.adriansteel.com/>


From: Patrick Ziegler ***@***.***>
Sent: Tuesday, October 10, 2023 3:16 PM
To: eclipse-windowbuilder/windowbuilder ***@***.***>
Cc: Cindy Cunningham ***@***.***>; State change ***@***.***>
Subject: [EXTERNAL] Re: [eclipse-windowbuilder/windowbuilder] WindowBuilder was not able to show the GUI (Issue #533)

You don't often get email from ***@***.******@***.***>. Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

Installed WindowBuilder and can not get the Design tab. Even without attempting to set my compiler to Java 8.

What's the error you got? If you've attached a screenshot to previous your email, then it hasn't been uploaded to GitHub.

Is Neon still available if we want to revert back?

The release will always be available for the foreseeable future: https://www.eclipse.org/downloads/packages/release/Neon/3
There is just no guarantee that it'll be compatible with the latest WindowBuilder, though.

-

**Comment by ptziegler** [comment] 2023-11-05 14:49
I'm closing this as "Not Planned". From what I can tell, this problem exclusively shows up with Java 8, but not with any newer JDK. Given that Java 8 is slowly phased out, I don't think it's worth spending much time trying to figure out what exactly goes wrong here, especially because I believe it's a combination between WindowBuilder and JDT.

**Closed by ptziegler** 2023-11-05 14:49 UTC
