### ISSUE TITLE
Unknown GUI toolkit

### ISSUE THREAD

**Issue by Almusavveer** [eclipse-windowbuilder/windowbuilder#619] opened 2023-11-02 16:33 UTC
I was trying to create Java Application using WindowBuilder but it show this issue
![issue](https://github.com/eclipse-windowbuilder/windowbuilder/assets/67317335/4284f1b0-08f9-4a19-b29b-205eba4a86af)

**Comment by ptziegler** [comment] 2023-11-02 16:42
Duplicate of #620

**Closed by ptziegler** 2023-11-02 16:42 UTC
