### ISSUE TITLE
dysfonctionnement du design de poste de travail de java

### ISSUE THREAD

**Issue by yedess70** [eclipse-windowbuilder/windowbuilder#920] opened 2024-10-08 18:38 UTC
dysfonctionnement du design de poste de travail de java

**Comment by yedess70** [comment] 2024-10-08 18:51
Il m'affiche une erreur interne
[capture java error.docx](https://github.com/user-attachments/files/17297887/capture.java.error.docx)
[capture java [](error.docx](https://github.com/user-attachments/files/17297907/capture.java.error.docx))

**Comment by ptziegler** [comment] 2024-10-09 04:44
It would be really great to communicate in a language both of us can understand...

But based on the screenshot, I'm suspecting a broken WindowBuilder installation, so let me quote myself on a related issue:
https://github.com/eclipse-windowbuilder/windowbuilder/discussions/913#discussioncomment-10853917
> > org.eclipse.wb.xwt_1.9.0.201608250402
> 
> That's quite an old version you updated from. The XWT component has been removed with the 1.15, so it's likely that it wasn't properly uninstalled after the update.
> 
> You can try to explicitly uninstall the XWT component via **Help** -> **About Eclipse IDE** -> **Installation Details** and see if that helps or go the nuclear version and simply set up a fresh IDE and import any additional plugins (WindowBuilder excluded) from the previous installation. ![image](https://private-user-images.githubusercontent.com/70652978/373891172-60263215-f4c4-45e5-a440-97fb22f361ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NDkyNDgsIm5iZiI6MTcyODQ0ODk0OCwicGF0aCI6Ii83MDY1Mjk3OC8zNzM4OTExNzItNjAyNjMyMTUtZjRjNC00NWU1LWE0NDAtOTdmYjIyZjM2MWVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDA0NDIyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxMGJiZWQ0ZjFiMDVhNGFiY2Y1ZmJjNTgzNWU3Y2U0ZGM0N2ZlZGRlODNkOWFjNTU4OTYzMjJmMDcwYTdjZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EURzSakCp_Bbdr6__3Kk0gg5qrlRszZXXHqhV0WSUEE)



> > org.eclipse.wb.xwt_1.9.0.201608250402
> 
> That's quite an old version you updated from. The XWT component has been removed with the 1.15, so it's likely that it wasn't properly uninstalled after the update.
> 
> You can try to explicitly uninstall the XWT component via **Help** -> **About Eclipse IDE** -> **Installation Details** and see if that helps or go the nuclear version and simply set up a fresh IDE and import any additional plugins (WindowBuilder excluded) from the previous installation. ![image](https://private-user-images.githubusercontent.com/70652978/373891172-60263215-f4c4-45e5-a440-97fb22f361ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NDkyNDgsIm5iZiI6MTcyODQ0ODk0OCwicGF0aCI6Ii83MDY1Mjk3OC8zNzM4OTExNzItNjAyNjMyMTUtZjRjNC00NWU1LWE0NDAtOTdmYjIyZjM2MWVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDA0NDIyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxMGJiZWQ0ZjFiMDVhNGFiY2Y1ZmJjNTgzNWU3Y2U0ZGM0N2ZlZGRlODNkOWFjNTU4OTYzMjJmMDcwYTdjZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EURzSakCp_Bbdr6__3Kk0gg5qrlRszZXXHqhV0WSUEE)

**Comment by ptziegler** [comment] 2024-10-09 04:45
Duplicate of #782

**Closed by ptziegler** 2024-10-09 04:45 UTC
Labels: duplicate
