### ISSUE TITLE
Lambda expressions for buttons causes eclipse to hang

### ISSUE THREAD

**Issue by igarshep** [eclipse-windowbuilder/windowbuilder#729] opened 2024-03-19 19:52 UTC
I'm not entirely sure what triggers it, as some lambda expressions for buttons are fine, while others are not. I have verified that switching the method back to to a standard action listener action performed method works fine, so I suspect its related to it being in a lambda expression. 

Whatever is causing the lambda expression to be interpreted, causes eclipse to freeze indefinitely when switching to the design tab.

This is in windowbuilder 1.15 (current, I believe)

**Comment by ptziegler** [comment] 2024-03-20 17:15
Can you provide a small example or a short description on how to reproduce this problem?

**Comment by igarshep** [comment] 2024-03-21 20:16
I'm trying to figure out what it takes to reproduce it, it has something to do with the content of the lambda because as I start commenting lines out, at a certain point it starts working again. 

I am experiencing it on OSX.

Not sure if this is relevant, but in the process of trying to recreate the conditions, I went to the Properties tab of the menu item with a lambda expression, and saw this: 
<img width="252" alt="image" src="https://github.com/eclipse-windowbuilder/windowbuilder/assets/30322202/722a9640-4ece-48eb-a9fc-c212a3c98ada">
If I double click, even though it does not change anything in the code, I get this stack trace:
`java.lang.ClassNotFoundException: org.eclipse.jdt.core.dom.LambdaTypeStub cannot be found by org.eclipse.jdt.core_3.37.0.v20240215-1452
	at org.eclipse.osgi.internal.loader.BundleLoader.generateException(BundleLoader.java:562)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:557)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:434)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:174)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at org.eclipse.wb.internal.core.utils.ast.LambdaTypeDeclaration.create(LambdaTypeDeclaration.java:35)
	at org.eclipse.wb.internal.core.model.property.event.ListenerMethodProperty.findListenerType(ListenerMethodProperty.java:251)
	at org.eclipse.wb.internal.core.model.property.event.ListenerMethodProperty.findListenerMethod(ListenerMethodProperty.java:795)
	at org.eclipse.wb.internal.core.model.property.event.ListenerMethodProperty.findStubMethod(ListenerMethodProperty.java:996)
	at org.eclipse.wb.internal.core.model.property.event.ListenerMethodProperty.openStubMethod(ListenerMethodProperty.java:816)
	at org.eclipse.wb.internal.core.model.property.event.ListenerMethodPropertyEditor$1.run(ListenerMethodPropertyEditor.java:90)
	at org.eclipse.wb.internal.core.utils.execution.ExecutionUtils.run(ExecutionUtils.java:331)
	at org.eclipse.wb.internal.core.model.property.event.ListenerMethodPropertyEditor.openStubMethod(ListenerMethodPropertyEditor.java:87)
	at org.eclipse.wb.internal.core.model.property.event.ListenerMethodPropertyEditor.doubleClick(ListenerMethodPropertyEditor.java:65)
	at org.eclipse.wb.internal.core.model.property.table.PropertyTable.handleMouseDoubleClick(PropertyTable.java:400)
	at org.eclipse.wb.internal.core.model.property.table.PropertyTable$1.mouseDoubleClick(PropertyTable.java:167)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:200)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4643)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1524)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1547)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1532)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1325)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4410)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3986)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1042)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:152)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:639)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:546)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)`

**Comment by ptziegler** [comment] 2024-03-21 20:38
> java.lang.ClassNotFoundException: org.eclipse.jdt.core.dom.LambdaTypeStub

Curious... it seems like [org.eclipse.wb.jdt.fragment](https://github.com/eclipse-windowbuilder/windowbuilder/tree/master/org.eclipse.wb.jdt.fragment) was never part of any release and therefore this mechanism couldn't have worked on a user workpace.

**Comment by ptziegler** [comment] 2024-03-21 20:57
And the reason this issue doesn't happen for the standard action listeners because we've checked in the [class](https://github.com/eclipse-windowbuilder/windowbuilder/blob/master/org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/utils/ast/AnonymousTypeDeclaration2.clazz) file... That's nasty.

**Closed** 2024-04-02 20:34 UTC
Labels: bug, question

**Comment by ptziegler** [comment] 2024-04-02 20:35
@igarshep @rosennej Can you two check with tomorrows nightly build whether this issue still persists?

**Comment by rosennej** [comment] 2024-04-03 20:43
I tested it superficially and it works fine.

However, the update failed with the message "operation plan must be resolved" so I uninstalled WindowBuilder and reinstalled it in order to test it.

This is the error log:
eclipse.buildId=4.31.0.20240307-1200
java.version=17.0.10
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product

org.eclipse.epp.mpc.ui
Error
Wed Apr 03 23:19:21 IDT 2024
Problems occurred while performing provisioning operation: operation plan must be resolved

java.lang.IllegalStateException: operation plan must be resolved
          at org.eclipse.equinox.internal.p2.ui.ProvUI.toCurrentJREOperation(ProvUI.java:338)
          at org.eclipse.equinox.internal.p2.ui.ProvUI.toCompabilityWithCurrentJREProvisioningPlan(ProvUI.java:325)
          at org.eclipse.epp.internal.mpc.ui.wizards.MarketplaceWizard.lambda$5(MarketplaceWizard.java:876)
          at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:124)

Best Regards,

Jonathan Rosenne

**Comment by ptziegler** [comment] 2024-04-04 04:38
```
java.lang.IllegalStateException: operation plan must be resolved
          at org.eclipse.equinox.internal.p2.ui.ProvUI.toCurrentJREOperation(ProvUI.java:338)
          at org.eclipse.equinox.internal.p2.ui.ProvUI.toCompabilityWithCurrentJREProvisioningPlan(ProvUI.java:325)
          at org.eclipse.epp.internal.mpc.ui.wizards.MarketplaceWizard.lambda$5(MarketplaceWizard.java:876)
          at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:124)
```

That's a very weird error message... I've just tried installing the nightly build with the latest [Eclipse IDE for Java Developers](https://www.eclipse.org/downloads/packages/release/2024-03/r/eclipse-ide-java-developers) without problems. Perhaps this was just a fluke?

**Comment by rosennej** [comment] 2024-04-04 06:27
I am using a freshly installed Eclipse 2024-03:

Eclipse IDE for Enterprise Java and Web Developers (includes Incubating components)

Version: 2024-03 (4.31.0)
Build id: 20240307-1437

Attached is my configuration. It could have been a fluke.

Best Regards,

Jonathan Rosenne

**Comment by ptziegler** [comment] 2024-04-04 16:42
> I wonder what I can do to debug this.

If it's stuck, then I would suggest to profile the IDE via [VisualVM](https://visualvm.github.io/). If you can take and upload a snapshot of e.g. the sampler, I can also take a look at it.

**Comment by ptziegler** [comment] 2024-04-04 20:08
@igarshep Thanks! That helped me reproduce the issue. Hm... it seems like this is a general problem when lambda expressions are used and not just something exclusive to the listeners. Here's a small variation of your example, which suffers from the same problem.

```
public class MainUI extends JPanel {
	public MainUI() {

		final JButton btnNewButton = new JButton("New button");
		btnNewButton.addActionListener(new ActionListener() {
			public void actionPerformed(final ActionEvent arg0) {
				System.out.println("test");
				WindowInstance picker = new WindowInstance();
			}
		});
		test(() -> {
			System.out.println("test");
			WindowInstance picker = new WindowInstance();
		});
		add(btnNewButton);
	}

	private void test(Runnable r) {
		r.run();
	}
}
```

**Comment by ptziegler** [comment] 2024-04-04 20:30
@igarshep After simplifying the problem further, I think this is a conceptional problem with the code.

This is the minimal reproducer I came up with, based on your example:

```
public class MyFrame extends JFrame {
	public static void main(String[] args) {
		new MyFrame();
	}

	public MyFrame() {
		new MyDialog();
		System.out.println("All done~");
	}

	public static class MyDialog extends JDialog {
		public MyDialog() {
			setModal(true);
			setVisible(true);
		}
	}
}
```
If I try to run this class using the `main` method, the code blocks indefinitely. If I comment out `setModal(true)`, then everything works and the string is printed to the console.

The same can be observed with your example. And if it doesn't even work with plain Java, I'm not sure how WindowBuilder can do a better job...

**Comment by igarshep** [comment] 2024-04-04 20:45
What you described is standard modal behavior, its mostly the whole point. If I run your example, a window with just the close/minimize buttons comes up. If you close the window, then you get the string printed.

However, this isn't the behavior that seems to be the problem. There's clearly a difference in my example between a lambda calling the same set of code vs a standard action listener. If I toggle between one by commenting out the other, I get different behavior with the lambda causing eclipse to hang.

**Comment by rosennej** [comment] 2024-04-04 21:01
Is this a valid lambda? Doesn't it have side effects?

Best Regards,

Jonathan Rosenne

**Comment by ptziegler** [comment] 2024-04-04 21:01
> What you described is standard modal behavior, its mostly the whole point. If I run your example, a window with just the close/minimize buttons comes up. If you close the window, then you get the string printed.

Right... apologies. I didn't notice the small frame popping up. 
But you have the same behavior with WindowBuilder. The modal dialog is opened, blocking WindowBuilder from switching to the 

>  There's clearly a difference in my example between a lambda calling the same set of code vs a standard action listener.

When using the lambda expression, WindowBuilder tries to create a proper instance of the dialog, while it doesn't with anonymous classes. My point is that this is a general problem that will pop whenever modal dialogs are used, not just with listeners or lambda expressions.

**Comment by ptziegler** [comment] 2024-04-04 21:17
I've created #741 to keep track of the issue. As mentioned, the problem is the modal dialog. The lambda expression is merely the catalyst, but not the cause.
